FROM crpi-g0cm9l3tvvpecg9b.cn-shanghai.personal.cr.aliyuncs.com/pushihao/ohpc:base
LABEL maintainer="pushihao@njust.edu.cn"

# Base compute node
RUN curl -fsSL https://github.com/saltstack/salt-install-guide/releases/latest/download/salt.repo | tee /etc/yum.repos.d/salt.repo && \
    dnf install -y ohpc-base-compute ohpc-slurm-client \
                   patch file zstd bzip2 xz python3 gcc-c++ gcc-gfortran \
                   salt-minion && \
    dnf clean all && \
    echo "master: head" >> /etc/salt/minion

# Copy configuration
COPY ssh_config/sshd_config /etc/ssh/sshd_config
COPY custom_script/user_task_end.sh /etc/slurm/epilog.sh
COPY custom_script/user_task_begin.sh /etc/slurm/prolog.sh

# Script
RUN mkdir /var/log/slurm && \
    chmod +x /etc/slurm/prolog.sh /etc/slurm/epilog.sh

# Set root password
RUN echo 'root:root' | chpasswd

# Run after run
RUN echo "rm -f /var/run/nologin" >> /etc/rc.local && \
    chmod +x /etc/rc.local

# Enable service
COPY systemd_config/slurmd_override.conf /etc/systemd/system/slurmd.service.d/override.conf
RUN systemctl enable munge dbus.socket slurmd sshd salt-minion

# Use systemd
CMD ["/usr/sbin/init"]
