FROM ohpc-container/openhpc:3
LABEL maintainer="pushihao@njust.edu.cn"

ENV http_proxy='http://10.10.11.82:9500'
ENV https_proxy='http://10.10.11.82:9500'
RUN export https_proxy=http://10.10.11.82:9500 http_proxy=http://10.10.11.82:9500 all_proxy=socks5://10.10.11.82:9501

# Base install
RUN dnf install -y ohpc-slurm-server && \
    dnf install -y inotify-tools

# Install Salt
RUN rpm --import https://repo.saltproject.io/salt/py3/redhat/9/x86_64/SALT-PROJECT-GPG-PUBKEY-2023.pub && \
    curl -fsSL https://repo.saltproject.io/salt/py3/redhat/9/x86_64/latest.repo | sudo tee /etc/yum.repos.d/salt.repo && \
    dnf install -y salt-master

# Salt sync config
RUN mkdir -p /srv/salt/auth_files && mkdir -p /var/log/slurm
COPY sync_auth_files.sls /srv/salt/sync_auth_files.sls

# Copy configuration
COPY slurm.conf /etc/slurm/slurm.conf
COPY slurmdbd.conf /etc/slurm/slurmdbd.conf
COPY cgroup.conf /etc/slurm/cgroup.conf
COPY sshd_config /etc/ssh/sshd_config
COPY gres.conf /etc/slurm/gres.conf

# File permissions
RUN chown slurm:slurm /etc/slurm/slurmdbd.conf && chmod 600 /etc/slurm/slurmdbd.conf && \
    touch /var/log/slurmdbd.log && \
    touch /var/log/slurmctld.log && chown slurm:slurm /var/log/slurmctld.log && chmod 640 /var/log/slurmctld.log && \
    touch /var/log/munge/munged.log && chown -R munge:munge /var/log/munge && chmod 640 /var/log/munge/munged.log

# Set root password
RUN echo 'root:root' | chpasswd

# Delete nologin file
RUN echo "rm -f /var/run/nologin" >> /etc/rc.local && \
    chmod +x /etc/rc.local

# Define service boot order
COPY slurmctld_override.conf /etc/systemd/system/slurmctld.service.d/override.conf

# Copy Script
COPY monitor_user.sh /usr/local/bin/monitor_user.sh
RUN chmod +x /usr/local/bin/monitor_user.sh

# Enable service
COPY monitor-user.service /etc/systemd/system/monitor-user.service
RUN systemctl enable munge && \
    systemctl enable slurmdbd && \
    systemctl enable slurmctld && \
    systemctl enable sshd && \
    systemctl enable monitor-user && \
    systemctl enable salt-master

# Use systemd
CMD ["/usr/sbin/init"]
