FROM ohpc-container/openhpc:3
LABEL maintainer="pushihao@njust.edu.cn"

ENV http_proxy='http://192.168.246.29:7890'
ENV https_proxy='http://192.168.246.29:7890'

RUN dnf install -y supervisor && \
    dnf install -y ohpc-slurm-server && \
    dnf install -y openssh-server

# Copy Configuration
COPY slurm.conf /etc/slurm/slurm.conf
COPY slurmdbd.conf /etc/slurm/slurmdbd.conf
COPY cgroup.conf /etc/slurm/cgroup.conf
COPY sshd_config /etc/ssh/sshd_config
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# SSH Service
RUN ssh-keygen -A

# File Permissions
RUN chown slurm:slurm /etc/slurm/slurmdbd.conf && \
    chmod 600 /etc/slurm/slurmdbd.conf && \
    mkdir /var/log/slurm && touch /var/log/slurm/slurmdbd.log && \
    chmod 755 /var/log && \
    chown root:root /var/log/munge/ && \
    chmod 600 /var/log/munge/

# Set root password
RUN echo 'root:root' | chpasswd

# Use Supervisor For Multi-Program
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
