FROM ohpc-container/openhpc:3
LABEL maintainer="pushihao@njust.edu.cn"

ENV http_proxy='http://10.10.11.82:9500'
ENV https_proxy='http://10.10.11.82:9500'

# Base install
RUN dnf install -y ohpc-slurm-server ipa-client

# Install IPA-client
COPY ipa-client-install.sh /usr/tmp/ipa-client-install.sh
RUN chmod +x /usr/tmp/ipa-client-install.sh

# Copy configuration
COPY slurm.conf /etc/slurm/slurm.conf
COPY slurmdbd.conf /etc/slurm/slurmdbd.conf
COPY cgroup.conf /etc/slurm/cgroup.conf
COPY sshd_config /etc/ssh/sshd_config

# File permissions
RUN chown slurm:slurm /etc/slurm/slurmdbd.conf && chmod 600 /etc/slurm/slurmdbd.conf && \
    mkdir /var/log/slurm && touch /var/log/slurm/slurmdbd.log && \
    touch /var/log/slurmctld.log && chown slurm:slurm /var/log/slurmctld.log && chmod 640 /var/log/slurmctld.log && \
    touch /var/log/munge/munged.log && chown -R munge:munge /var/log/munge && chmod 640 /var/log/munge/munged.log

# Set root password
RUN echo 'root:root' | chpasswd

# Start service
RUN systemctl enable munge && \
    systemctl enable slurmdbd && \
    systemctl enable slurmctld && \
    systemctl enable sshd

# Use systemd
CMD ["/usr/sbin/init"]
