FROM registry.docker.com/library/rockylinux:9
LABEL maintainer="pushihao@njust.edu.cn"

# Base install
ARG ARCH=x86_64

RUN dnf install -y http://repos.openhpc.community/OpenHPC/3/EL_9/$ARCH/ohpc-release-3-1.el9.$ARCH.rpm && \
    dnf install -y dnf-plugins-core && \
    dnf config-manager --set-enabled crb && \
    dnf upgrade -y && \
    dnf swap -y curl-minimal curl && \
    dnf groupinstall "Development Tools" && \
    dnf install -y curl unzip jq procps-ng iproute bind-utils findutils ohpc-base \
        iputils vim rsync unzip git sendmail postfix openssh-server munge tmux screen && \
    dnf -y install systemd systemd-libs && \
    (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done) && \
    rm -f /lib/systemd/system/multi-user.target.wants/* && \
    rm -f /etc/systemd/system/*.wants/* && \
    rm -f /lib/systemd/system/local-fs.target.wants/* && \
    rm -f /lib/systemd/system/sockets.target.wants/*udev* && \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl* && \
    rm -f /lib/systemd/system/basic.target.wants/* && \
    rm -f /lib/systemd/system/anaconda.target.wants/* && \
    /usr/sbin/create-munge-key && \
    ssh-keygen -A && \
    dnf clean all && \
    rm -rf /var/cache/dnf/*

