FROM crpi-g0cm9l3tvvpecg9b.cn-shanghai.personal.cr.aliyuncs.com/pushihao/ohpc:base
LABEL maintainer="pushihao@njust.edu.cn"

# Base install
RUN dnf install -y ohpc-slurm-server && \
    dnf clean all

# Enable service
RUN systemctl enable munge slurmdbd

# Use systemd
CMD ["/usr/sbin/init"]
