FROM ohpc-container/openhpc:3
LABEL maintainer="pushihao@njust.edu.cn"

## Base compute node
RUN dnf install -y ohpc-base-compute ohpc-slurm-client lmod-ohpc \
    git patch file zstd bzip2 xz \
    python3 python3-pip \
    gcc-c++ gcc-gfortran \
    ohpc-gnu13-runtimes gnu13-compilers-ohpc \ 
    openmpi5-pmix-gnu13-ohpc openblas-gnu13-ohpc netcdf-gnu13-openmpi5-ohpc \
    openssh-server \
    supervisor

RUN dnf install -y spack-ohpc ohpc-gnu13-openmpi5-parallel-libs \
    ohpc-gnu13-python-libs ohpc-gnu13-runtimes

# SSH Service
RUN ssh-keygen -A
COPY sshd_config /etc/ssh/sshd_config

# Pam Slurm Adopt
COPY pam.d/sshd /etc/pam.d/sshd
COPY pam.d/system-auth /etc/pam.d/system-auth
COPY pam.d/password-auth /etc/pam.d/password-auth
RUN echo "root" > /etc/ssh/allowed_users_file && chmod 600 /etc/ssh/allowed_users_file

# User Supervisor For Multi-Program
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
CMD ["usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
