FROM ohpc-container/openhpc:3
LABEL maintainer="pushihao@njust.edu.cn"

ENV http_proxy='http://10.10.11.82:9500'
ENV https_proxy='http://10.10.11.82:9500'
RUN export https_proxy=http://10.10.11.82:9500 http_proxy=http://10.10.11.82:9500 all_proxy=socks5://10.10.11.82:9501

# Base compute node
RUN dnf install -y ohpc-base-compute ohpc-slurm-client lmod-ohpc && \
    dnf install -y git patch file zstd bzip2 xz && \
    dnf install -y python3 python3-pip && \
    dnf install -y gcc-c++ gcc-gfortran && \
    dnf install -y ohpc-gnu13-runtimes gnu13-compilers-ohpc && \ 
    dnf install -y openmpi5-pmix-gnu13-ohpc openblas-gnu13-ohpc netcdf-gnu13-openmpi5-ohpc && \
    dnf install -y spack-ohpc ohpc-gnu13-openmpi5-parallel-libs && \
    dnf install -y ohpc-gnu13-python-libs ohpc-gnu13-runtimes

# Install Salt
RUN rpm --import https://repo.saltproject.io/salt/py3/redhat/9/x86_64/SALT-PROJECT-GPG-PUBKEY-2023.pub && \
    curl -fsSL https://repo.saltproject.io/salt/py3/redhat/9/x86_64/latest.repo | sudo tee /etc/yum.repos.d/salt.repo && \
    dnf install -y salt-minion
RUN echo "master: head.example.com" >> /etc/salt/minion

# SSH configuration
COPY sshd_config /etc/ssh/sshd_config

# Pam Slurm Adopt
COPY pam.d/sshd /etc/pam.d/sshd
COPY pam.d/system-auth /etc/pam.d/system-auth
COPY pam.d/password-auth /etc/pam.d/password-auth
RUN echo "root" > /etc/ssh/allowed_users_file && chmod 600 /etc/ssh/allowed_users_file

# Set root password
RUN echo 'root:root' | chpasswd

# Run after run
RUN echo "rm -f /var/run/nologin" >> /etc/rc.local && \
    echo "mount -o remount,rw /sys/fs/cgroup" >> /etc/rc.local && \
    echo "chmod -R u+w /sys/fs/cgroup" >> /etc/rc.local && \
    chmod +x /etc/rc.local

# Prolog && Epilog
COPY prolog.sh /etc/slurm/prolog.sh
COPY epilog.sh /etc/slurm/epilog.sh
COPY check_GPU.sh /etc/slurm/check_GPU.sh
RUN mkdir /var/log/slurm && \
    chmod +x /etc/slurm/prolog.sh && \
    chmod +x /etc/slurm/epilog.sh && \
    chmod +x /etc/slurm/check_GPU.sh

# Slurmd service need some extra parameter
COPY slurmd_override.conf /etc/systemd/system/slurmd.service.d/override.conf

# Enable service
RUN systemctl enable munge && \
    systemctl enable slurmd && \
    systemctl enable sshd && \
    systemctl enable salt-minion

# Use systemd
CMD ["/usr/sbin/init"]
