FROM ohpc-container/openhpc:3
LABEL maintainer="pushihao@njust.edu.cn"

ENV http_proxy='http://10.10.11.82:9500'
ENV https_proxy='http://10.10.11.82:9500'
RUN export https_proxy=http://10.10.11.82:9500 http_proxy=http://10.10.11.82:9500 all_proxy=socks5://10.10.11.82:9501

# Base compute node
RUN rpm --import https://repo.saltproject.io/salt/py3/redhat/9/x86_64/SALT-PROJECT-GPG-PUBKEY-2023.pub && \
    curl -fsSL https://repo.saltproject.io/salt/py3/redhat/9/x86_64/latest.repo | sudo tee /etc/yum.repos.d/salt.repo && \
    dnf install -y ohpc-base-compute ohpc-slurm-client lmod-ohpc \
                   git patch file zstd bzip2 xz python3 python3-pip gcc-c++ gcc-gfortran \
                   ohpc-gnu13-runtimes gnu13-compilers-ohpc spack-ohpc ohpc-gnu13-openmpi5-parallel-libs \ 
                   openmpi5-pmix-gnu13-ohpc openblas-gnu13-ohpc netcdf-gnu13-openmpi5-ohpc \
                   ohpc-gnu13-python-libs ohpc-gnu13-runtimes \
                   salt-minion && \
    dnf clean all && \
    echo "master: head.example.com" >> /etc/salt/minion

# Copy configuration
COPY sshd_config /etc/ssh/sshd_config
COPY pam.d/sshd pam.d/system-auth pam.d/password-auth /etc/pam.d/

# Allow root login && Set root password
RUN echo "root" > /etc/ssh/allowed_users_file && chmod 600 /etc/ssh/allowed_users_file && \
    echo 'root:root' | chpasswd

# Run after run
RUN echo "rm -f /var/run/nologin" >> /etc/rc.local && \
    echo "mount -o remount,rw /sys/fs/cgroup" >> /etc/rc.local && \
    echo "chmod -R u+w /sys/fs/cgroup" >> /etc/rc.local && \
    chmod +x /etc/rc.local

# Prolog && Epilog
COPY prolog.sh epilog.sh check_GPU.sh /etc/slurm/
RUN mkdir /var/log/slurm && \
    chmod +x /etc/slurm/prolog.sh /etc/slurm/epilog.sh /etc/slurm/check_GPU.sh

# Enable service
COPY slurmd_override.conf /etc/systemd/system/slurmd.service.d/override.conf
RUN systemctl enable munge dbus.socket slurmd sshd salt-minion

# Use systemd
CMD ["/usr/sbin/init"]
