FROM ohpc-container/openhpc:3
LABEL maintainer="pushihao@njust.edu.cn"

ENV http_proxy='http://10.10.11.82:9500'
ENV https_proxy='http://10.10.11.82:9500'

# Base compute node
RUN dnf install -y ohpc-base-compute ohpc-slurm-client lmod-ohpc \
    git patch file zstd bzip2 xz \
    python3 python3-pip \
    gcc-c++ gcc-gfortran \
    ohpc-gnu13-runtimes gnu13-compilers-ohpc \ 
    openmpi5-pmix-gnu13-ohpc openblas-gnu13-ohpc netcdf-gnu13-openmpi5-ohpc \
    spack-ohpc ohpc-gnu13-openmpi5-parallel-libs \
    ohpc-gnu13-python-libs ohpc-gnu13-runtimes \
    ipa-client

# Install IPA-client
COPY ipa-client-install.sh /usr/tmp/ipa-client-install.sh
RUN chmod +x /usr/tmp/ipa-client-install.sh
RUN /usr/tmp/ipa-client-install.sh

# SSH configuration
COPY sshd_config /etc/ssh/sshd_config

# Pam Slurm Adopt
COPY pam.d/sshd /etc/pam.d/sshd
COPY pam.d/system-auth /etc/pam.d/system-auth
COPY pam.d/password-auth /etc/pam.d/password-auth
RUN echo "root" > /etc/ssh/allowed_users_file && chmod 600 /etc/ssh/allowed_users_file

# Set root password
RUN echo 'root:root' | chpasswd

# Delete nologin file
RUN echo "rm -f /var/run/nologin" >> /etc/rc.local && \
    chmod +x /etc/rc.local

# Slurmd service need some extra parameter
COPY slurmd_override.conf /etc/systemd/system/slurmd.service.d/override.conf

# Enable service
RUN systemctl enable munge && \
    systemctl enable slurmd && \
    systemctl enable sshd

# Use systemd
CMD ["/usr/sbin/init"]
