FROM ohpc-container/openhpc:3
LABEL maintainer="pushihao@njust.edu.cn"

ENV http_proxy='http://10.10.11.82:9500'
ENV https_proxy='http://10.10.11.82:9500'

# Install FreeIPA server package
RUN dnf install -y ipa-server ipa-server-dns
COPY ipa-server-install.sh /usr/tmp/ipa-server-install.sh
RUN chmod +x /usr/tmp/ipa-server-install.sh

# SSH service
COPY sshd_config /etc/ssh/sshd_config

# Set root password
RUN echo 'root:root' | chpasswd

# Delete nologin file
RUN echo "rm -f /var/run/nologin" >> /etc/rc.local && \
    chmod +x /etc/rc.local

# Enable service
RUN systemctl enable ipa && \
    systemctl enable sshd

# Use systemd
CMD ["/usr/sbin/init"]
