FROM ohpc-container/openhpc:3
LABEL maintainer="pushihao@njust.edu.cn"

ENV http_proxy='http://10.10.11.82:9500'
ENV https_proxy='http://10.10.11.82:9500'

# Install FreeIPA
RUN dnf install -y ipa-server ipa-server-dns bind-utils
COPY ipa-server-install.sh /usr/tmp/ipa-server-install.sh
RUN chmod +x /usr/tmp/ipa-server-install.sh

# Set root password
RUN echo 'root:root' | chpasswd

# SSH configuration
COPY sshd_config /etc/ssh/sshd_config

# Start service
RUN systemctl enable sshd

# Use systemd
CMD ["/usr/sbin/init"]
