name: Build Container

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Make scripts executable
      run: |
        chmod +x build-control-node.sh
        chmod +x build-compute-node.sh

    - name: Build Control Node Image
      run: |
        ./build-control-node.sh

    - name: Build Compute Node Image
      run: |
        ./build-compute-node.sh

    - name: Save Control Node Image as Tar
      run: |
        podman save -o head.tar localhost/ohpc-container/head

    - name: Save Compute Node Image as Tar
      run: |
        podman save -o compute.tar localhost/ohpc-container/compute

    - name: Upload Container Image Tar Files
      uses: actions/upload-artifact@v4
      with:
        name: container-images
        path: |
          head.tar
          compute.tar
