name: Build Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Images
      run: |
        podman build -t ohpc-container/openhpc:3 -f openhpc/Containerfile openhpc
        podman build -t ohpc-container/head -f head/Containerfile head
        podman build -t ohpc-container/compute -f compute/Containerfile compute

    - name: Save Images as Tar
      run: |
        podman save -o head.tar localhost/ohpc-container/head
        podman save -o compute.tar localhost/ohpc-container/compute

    - name: Upload Images Tar Files
      uses: actions/upload-artifact@v4
      with:
        name: OHPC-Images
        path: |
          head.tar
          compute.tar
