name: Build Images

on:
  workflow_dispatch:
    inputs:
      build_base:
        description: "Build Base container image"
        required: false
        default: "false"
      build_control:
        description: "Build control container image"
        required: false
        default: "false"
      build_login:
        description: "Build login container image"
        required: false
        default: "false"
      build_compute:
        description: "Build compute container image"
        required: false
        default: "false"
      build_openldap:
        description: "Build openldap container image"
        required: false
        default: "false"
      build_portal:
        description: "Build portal container image"
        required: false
        default: "false"

jobs:
  build_base:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build_base == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%y-%m-%d')" >> $GITHUB_ENV

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_ALI_USERNAME }}
          password: ${{ secrets.DOCKER_ALI_PASSWORD }}
          registry: crpi-g0cm9l3tvvpecg9b.cn-shanghai.personal.cr.aliyuncs.com

      - name: Build and push base container image
        uses: docker/build-push-action@v6.10.0
        with:
          context: ./openhpc
          file: ./openhpc/Containerfile
          push: true
          tags: crpi-g0cm9l3tvvpecg9b.cn-shanghai.personal.cr.aliyuncs.com/pushihao/ohpc:base-${{ env.DATE }}

  build_control:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build_control == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%y-%m-%d')" >> $GITHUB_ENV

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_ALI_USERNAME }}
          password: ${{ secrets.DOCKER_ALI_PASSWORD }}
          registry: crpi-g0cm9l3tvvpecg9b.cn-shanghai.personal.cr.aliyuncs.com

      - name: Build and push control container image
        uses: docker/build-push-action@v6.10.0
        with:
          context: ./control
          file: ./control/Containerfile
          push: true
          tags: crpi-g0cm9l3tvvpecg9b.cn-shanghai.personal.cr.aliyuncs.com/pushihao/ohpc:control-${{ env.DATE }}

  build_login:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build_login == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%y-%m-%d')" >> $GITHUB_ENV

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_ALI_USERNAME }}
          password: ${{ secrets.DOCKER_ALI_PASSWORD }}
          registry: crpi-g0cm9l3tvvpecg9b.cn-shanghai.personal.cr.aliyuncs.com

      - name: Build and push login container image
        uses: docker/build-push-action@v6.10.0
        with:
          context: ./login
          file: ./login/Containerfile
          push: true
          tags: crpi-g0cm9l3tvvpecg9b.cn-shanghai.personal.cr.aliyuncs.com/pushihao/ohpc:login-${{ env.DATE }}

  build_compute:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build_compute == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%y-%m-%d')" >> $GITHUB_ENV

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_ALI_USERNAME }}
          password: ${{ secrets.DOCKER_ALI_PASSWORD }}
          registry: crpi-g0cm9l3tvvpecg9b.cn-shanghai.personal.cr.aliyuncs.com

      - name: Build and push compute container image
        uses: docker/build-push-action@v6.10.0
        with:
          context: ./compute
          file: ./compute/Containerfile
          push: true
          tags: crpi-g0cm9l3tvvpecg9b.cn-shanghai.personal.cr.aliyuncs.com/pushihao/ohpc:compute-${{ env.DATE }}

  build_openldap:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build_openldap == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%y-%m-%d')" >> $GITHUB_ENV

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_ALI_USERNAME }}
          password: ${{ secrets.DOCKER_ALI_PASSWORD }}
          registry: crpi-g0cm9l3tvvpecg9b.cn-shanghai.personal.cr.aliyuncs.com

      - name: Build and push openldap container image
        uses: docker/build-push-action@v6.10.0
        with:
          context: ./openldap
          file: ./openldap/Containerfile
          push: true
          tags: crpi-g0cm9l3tvvpecg9b.cn-shanghai.personal.cr.aliyuncs.com/pushihao/ohpc:openldap-${{ env.DATE }}

  build_portal:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build_portal == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%y-%m-%d')" >> $GITHUB_ENV

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_ALI_USERNAME }}
          password: ${{ secrets.DOCKER_ALI_PASSWORD }}
          registry: crpi-g0cm9l3tvvpecg9b.cn-shanghai.personal.cr.aliyuncs.com

      - name: Build and push portal container image
        uses: docker/build-push-action@v6.10.0
        with:
          context: ./portal
          file: ./portal/Containerfile
          push: true
          tags: crpi-g0cm9l3tvvpecg9b.cn-shanghai.personal.cr.aliyuncs.com/pushihao/ohpc:portal-${{ env.DATE }}
