name: Build Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push OpenHPC container image
      uses: docker/build-push-action@v6.10.0
      with:
        context: ./openhpc
        file: ./openhpc/Containerfile
        push: true
        tags: pushihao/ohpc:base

    - name: Build and push head container image
      uses: docker/build-push-action@v6.10.0
      with:
        context: ./head
        file: ./head/Containerfile
        push: true
        tags: pushihao/ohpc:head

    - name: Build and push compute container image
      uses: docker/build-push-action@v6.10.0
      with:
        context: ./compute
        file: ./compute/Containerfile
        push: true
        tags: pushihao/ohpc:compute
