name: Build Images to Ali

on:
  workflow_dispatch:
    inputs:
      build_openhpc:
        description: "Build OpenHPC container image"
        required: false
        default: "false"
      build_head:
        description: "Build head container image"
        required: false
        default: "false"
      build_compute:
        description: "Build compute container image"
        required: false
        default: "false"

jobs:
  build_openhpc:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build_openhpc == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_ALI_USERNAME }}
          password: ${{ secrets.DOCKER_ALI_PASSWORD }}
          registry: crpi-g0cm9l3tvvpecg9b.cn-shanghai.personal.cr.aliyuncs.com

      - name: Build and push OpenHPC container image
        uses: docker/build-push-action@v6.10.0
        with:
          context: ./openhpc
          file: ./openhpc/Containerfile
          push: true
          tags: crpi-g0cm9l3tvvpecg9b.cn-shanghai.personal.cr.aliyuncs.com/pushihao/ohpc:base

  build_head:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build_head == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_ALI_USERNAME }}
          password: ${{ secrets.DOCKER_ALI_PASSWORD }}
          registry: crpi-g0cm9l3tvvpecg9b.cn-shanghai.personal.cr.aliyuncs.com

      - name: Build and push head container image
        uses: docker/build-push-action@v6.10.0
        with:
          context: ./head
          file: ./head/Containerfile
          push: true
          tags: crpi-g0cm9l3tvvpecg9b.cn-shanghai.personal.cr.aliyuncs.com/pushihao/ohpc:head

  build_compute:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build_compute == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_ALI_USERNAME }}
          password: ${{ secrets.DOCKER_ALI_PASSWORD }}
          registry: crpi-g0cm9l3tvvpecg9b.cn-shanghai.personal.cr.aliyuncs.com

      - name: Build and push compute container image
        uses: docker/build-push-action@v6.10.0
        with:
          context: ./compute
          file: ./compute/Containerfile
          push: true
          tags: crpi-g0cm9l3tvvpecg9b.cn-shanghai.personal.cr.aliyuncs.com/pushihao/ohpc:compute
